# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for Raman Spectroscopy Analysis Application
- Portable Executable
Generated: 2025-10-22 12:36:40
Python Version: 3.12.11
Platform: Windows AMD64

This file was auto-generated by generate_build_configs.py
DO NOT EDIT MANUALLY - regenerate using the script instead.
"""

from PyInstaller.utils.hooks import collect_submodules, collect_data_files
from pathlib import Path
import os
import sys

# Determine spec location
if '__file__' in globals():
    spec_path = Path(__file__).resolve()
else:
    candidate = Path(sys.argv[0]).resolve()
    if candidate.name != 'raman_app.spec':
        candidate = Path(os.getcwd()) / 'raman_app.spec'
    spec_path = candidate

spec_dir = spec_path.parent
project_root = spec_dir.parent if spec_dir.name == 'build_scripts' else spec_dir

# Add project root to sys.path
sys.path.insert(0, str(project_root))

# Initialize collections
datas = []
binaries = []
hiddenimports = []

# ============== DATA FILES ==============
# Assets (icons, fonts, locales)
assets_dir = os.path.join(str(project_root), 'assets')
if os.path.exists(assets_dir):
    datas += [(assets_dir, 'assets')]

# Functions module
functions_dir = os.path.join(str(project_root), 'functions')
if os.path.exists(functions_dir):
    datas += [(functions_dir, 'functions')]

# Configs module
configs_dir = os.path.join(str(project_root), 'configs')
if os.path.exists(configs_dir):
    datas += [(configs_dir, 'configs')]

# PySide6 plugins and data
datas += collect_data_files('PySide6')

# matplotlib mpl-data
datas += collect_data_files('matplotlib')

# ramanspy data files (if available)
try:
    datas += collect_data_files('ramanspy')
except Exception:
    pass

# ============== HIDDEN IMPORTS ==============
# Auto-detected imports from installed packages
hiddenimports += [
    "PySide6.QtCore",
    "PySide6.QtGui",
    "PySide6.QtWidgets",
    "PySide6.QtOpenGL",
    "PySide6.QtPrintSupport",
    "PySide6.QtSvg",
    "PySide6.QtSvgWidgets",
    "shiboken6",
    "numpy",
    "pandas",
    "scipy",
    "scipy.integrate",
    "scipy.signal",
    "scipy.interpolate",
    "scipy.optimize",
    "scipy.special",
    "scipy.stats",
    "scipy.stats._stats_py",
    "scipy.stats.distributions",
    "scipy.stats._distn_infrastructure",
    "scipy.linalg",
    "scipy.sparse",
    "scipy.ndimage",
    "matplotlib",
    "matplotlib.pyplot",
    "matplotlib.backends.backend_qt5agg",
    "matplotlib.figure",
    "matplotlib.widgets",
    "seaborn",
    "imageio",
    "ramanspy",
    "ramanspy.preprocessing",
    "ramanspy.preprocessing.normalise",
    "ramanspy.preprocessing.noise",
    "ramanspy.preprocessing.baseline",
    "pybaselines",
    "sklearn",
    "sklearn.preprocessing",
    "sklearn.decomposition",
    "sklearn.linear_model",
    "sklearn.ensemble",
    "sklearn.metrics",
    "sklearn.model_selection",
    "tqdm",
    "cloudpickle",
    "joblib",
    "pydantic"
]

# Collect submodules from key packages
try:
    hiddenimports += collect_submodules('ramanspy')
except Exception as e:
    print(f"Warning: Could not collect ramanspy submodules: {e}")

try:
    hiddenimports += collect_submodules('pybaselines')
except Exception as e:
    print(f"Warning: Could not collect pybaselines submodules: {e}")

# ============== BINARIES ==============
# Include DLL files for Andor SDK
dll_path = os.path.join(str(project_root), 'drivers')
if os.path.exists(dll_path):
    binaries += [
        (os.path.join(dll_path, 'atmcd32d.dll'), 'drivers'),
        (os.path.join(dll_path, 'atmcd64d.dll'), 'drivers'),
    ]

# ============== ANALYSIS ==============
a = Analysis(
    [os.path.join(str(project_root), 'main.py')],
    pathex=[str(project_root)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludedimports=['tkinter', 'matplotlib.backends.backend_tk'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

# ============== PYZ ==============
pyz = PYZ(a.pure, a.zipped_data, cipher=None)

# ============== EXE ==============
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='raman_app',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=True,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

# ============== BUNDLE ==============
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='raman_app',
)
