from enum import IntEnum

class StatusCode(IntEnum):
    DRV_SUCCESS = 20002
    DRV_VXDNOTINSTALLED = 20003
    DRV_ERROR_SCAN = 20004
    DRV_ERROR_CHECK_SUM = 20005
    DRV_ERROR_UNKNOW = 20006
    DRV_NO_NEW_DATA = 20073
    DRV_ACQUIRING = 20072
    DRV_IDLE = 20074
    DRV_NOT_INITIALIZED = 20075
    DRV_NOT_SUPPORTED = 20080
    DRV_TEMP_OFF = 20013
    DRV_TEMP_STABILIZED = 20036
    DRV_TEMP_NOT_REACHED = 20034
    DRV_TEMP_DRIFT = 20035

class AcquisitionMode(IntEnum):
    SINGLE_SCAN = 1
    ACCUMULATE = 2
    KINETIC = 3
    FAST_KINETIC = 4
    RUN_TILL_ABORT = 5

class ReadMode(IntEnum):
    FVB = 0
    SINGLE_TRACK = 1
    MULTI_TRACK = 2
    RANDOM_TRACK = 3
    FULL_IMAGE = 4

class TriggerMode(IntEnum):
    INTERNAL = 0
    EXTERNAL = 1
    EXTERNAL_START = 6
    EXTERNAL_EXPOSURE = 7
    SOFTWARE = 10

class ShutterMode(IntEnum):
    SHUTTER_CLOSED = 0
    SHUTTER_OPEN = 1
    SHUTTER_AUTO = 2

class ExposureError(IntEnum):
    EXPOSURE_TIME_INVALID = 20020
    ACQUISITION_IN_PROGRESS = 20024
    ACQUISITION_NOT_IN_PROGRESS = 20025
